bootstrapServers: localhost:9092

server:
  applicationConnectors:
  - type: http
    port: 8081
  adminConnectors:
  - type: http
    port: 8091

logging:
  level: INFO
  loggers:
    eu.hammarback: DEBUG
