bootstrapServers: localhost:9092

server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8090

logging:
  level: INFO
  loggers:
    eu.hammarback: DEBUG
