bootstrapServers: localhost:9092

server:
  applicationConnectors:
  - type: http
    port: 8082
  adminConnectors:
  - type: http
    port: 8092

logging:
  level: INFO
  loggers:
    eu.hammarback: DEBUG
